name: larch to S3

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  upload-larch-to-s3:
    name: Upload larch to S3
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Release Version
        id: get_version
        run: |
          VERSION=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq -r .tag_name)
          echo "Release version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Zip repository
        run: |
          zip -r "larch_${{ steps.get_version.outputs.version }}.zip" .
          zip -r "larch_latest.zip" .

      - name: ConfigureAWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::067782713062:role/admin-oidc
          role-session-name: ${{ github.repository_owner}}
          aws-region: us-east-1
      
      - name: Upload to S3
        run: |
          aws s3 cp "./larch_${{ steps.get_version.outputs.version }}.zip" s3://impact-repo-dependancies/larch/
          aws s3 cp "./larch_latest.zip" s3://impact-repo-dependancies/larch/